<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf5b78e238cc9069d65280df94d827759
{
    public static $prefixLengthsPsr4 = array (
        'J' =>
        array (
            'Jankx\\Extensions\\CouponSystem\\' => 30,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jankx\\Extensions\\CouponSystem\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf5b78e238cc9069d65280df94d827759::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf5b78e238cc9069d65280df94d827759::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf5b78e238cc9069d65280df94d827759::$classMap;

        }, null, ClassLoader::class);
    }
}
